language: java
jdk:
- oraclejdk8
notifications:
  email: false
  slack:
    secure: MPOYRFf0i49DhhQ2Pv5l8QemrKm4pW1NGDJK5d0wjTjgfYiixB+20xgTAFRDi9aBNj7S++DUCLYp9RLjb7GiwUCc5p7748L1TsAC1/6vubgZNUmH/vUJ65wYDf1CVV+gCpv4du77iwKGOi+v3aB/wtHDUJawzw7DVmLHFmVSf5//481s1UiA+19h6WoGhKqFIdz22B0eeF7ziwsb6KBfBYJnYYkHFNOWcdvIaNqKjxbaNTUa9Gs5JVvRMg2tI3KK361UPgdtRrOuR5C+aWyqyCPIUSz1xvtYP5kKpHm58WM+khz5avYg0HO2xUNzhPM2RjYsLz/88ssg99iXl2MT7ug5uVjS9XU7GBWkS9C64bS1DmEUJpAj6m1k5rxzwkgR9SBxVaxZdkMe4GvwP9t403SLYmOP4IVRXkOaX16kXEc3mnDiSlyu4sZ+PXOrfl2bTGkITO0JKVPxFkyAD+LpFhckamUnZ3t94C89NFo3smx+J3bKeKbp6PES67p/xFOhatREeK/N4cXVag+Y8LzbKI1WQj26NDflXedsef3abvGM5HmbIAamoSjRCIXwTanHZBGGgflvEgN/8ufnndYrEuNcFsFhIqerG83nOdJGVlLB3qL6ntp2TmFY0E5GMD5w4ybSOvJaJj6HDagcVU9OpEBt0IrWnzOg5ue+YQS7O0Y=
sudo: false
script: mvn verify
